import os
import re
import pandas as pd

RAW_DIR = "data/raw" 
TRACKS_CSV = "data/external/tracks.csv"
LIB_OUT = "data/processed/library.csv"

def load_tracks() -> pd.DataFrame:
    # Beginning of ChatGPT written code

    # tracks.csv has a 2-row header (album / comments etc.)
    df = pd.read_csv(TRACKS_CSV, header=[0, 1], index_col=0)

    # Flatten MultiIndex columns: ('track','title') -> 'track_title'
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [f"{a}_{b}" for a, b in df.columns]
    else:
        df.columns = [str(c) for c in df.columns]

    # End of ChatGPT written code

    df = df.reset_index()
    if "index" in df.columns and "track_id" not in df.columns:
        df = df.rename(columns={"index": "track_id"})

    def col(name: str):
        return df[name] if name in df.columns else pd.NA

    tracks = pd.DataFrame({
    "track_id": df["track_id"].astype(int),
    "title": col("track_title"),
    "artist": col("artist_name"),
    "genre_top": col("track_genre_top"),
    "duration": col("track_duration"),
    })

    return tracks


def scan_files() -> pd.DataFrame:
 rows = []
 for root, _, files in os.walk(RAW_DIR):
    for f in files:
        if not f.lower().endswith(".mp3"):
            continue
        m = re.match(r"(\d{6})\.mp3$", f)
        if m:
            tid = int(m.group(1))
        else:
            tid = pd.NA
        rel = os.path.join(root, f).replace("\\", "/")
        rows.append({"track_id": tid, "filename": f, "rel_path": rel})
 return pd.DataFrame(rows)


def main():
    tracks = load_tracks()
    files = scan_files()

    if files.empty:
        print(f"No MP3 files found under {RAW_DIR}")
        return

    files['track_id'] = files['track_id'].astype("Int64")
    tracks['track_id'] = tracks['track_id'].astype("Int64")

    lib = files.merge(tracks, on="track_id", how="left")

    # Fallbacks if metadata missing
    lib["title"] = lib["title"].fillna(lib["filename"])
    lib["artist"] = lib["artist"].fillna("Unknown Artist")
    lib["display"] = lib["title"] + " — " + lib["artist"]

    os.makedirs(os.path.dirname(LIB_OUT), exist_ok=True)
    lib.to_csv(LIB_OUT, index=False)
    print(f"Saved {LIB_OUT} with {len(lib)} rows")


if __name__ == "__main__":
    # checks flattening logic
    mi = pd.MultiIndex.from_tuples([("track", "title"), ("artist", "name")])
    flattened = [f"{a}_{b}" for a, b in mi]
    assert flattened == ["track_title", "artist_name"], f"Did not flatten correctly: {flattened}"

    # checks load_tracks - this test was generated by ChatGPT
    fake = pd.DataFrame(
        [["song", "artist"]],
        index=pd.Index([123456], name="track_id"),
        columns=pd.MultiIndex.from_tuples([("track", "title"), ("artist", "name")]),
    )

    orig_read_csv = pd.read_csv

    def fake_read_csv(path, header=None, index_col=None):
        return fake.copy()

    pd.read_csv = fake_read_csv
    try:
        tracks = load_tracks()
    finally:
        pd.read_csv = orig_read_csv

    assert list(tracks.columns[:3]) == ["track_id", "title", "artist"]
    assert int(tracks.loc[0, "track_id"]) == 123456

    print("All tests passed.\n")

    main()